frontend/src/lib/WebsocketConnection.tsx
This PR fixes https://github.com/streamlit/streamlit-old-private/issues/1098
=> 403 Error message

examples/core/dataframe_dimension_spec.py, frontend/cypress/integration/examples/core/dataframe_dimension_spec.spec.ts
I added an end2end test that verifies that the dimensions of a dataframe on the UI is as expected for different values of height and width parameters.
=> Add end2end test for st.dataframe width and height parameters

Dockerfile
=> Fix named volume for yarn-start cache in Docker file for Cypress

lib/tests/streamlit/hashing_test.py
This PR fixes this : https://streamlit.slack.com/archives/C9FJJN8Q7/p1568229744005400
=> Removing time dependent hashing tests

frontend/src/components/elements/Text/Text.tsx
https://github.com/streamlit/streamlit-old-private/issues/697
=> Escape html in markdown

lib/streamlit/config.py, lib/streamlit/magic.py
- Turn on magic by default
- Make magic not print variable name
=> Magic enhancements

docs/tutorial/create_an_interactive_report.md
Quick update for the slider code i two places. Change from interactive report to interactive app.
=> [Docs] Fix st.slider API in tutorial

e2e/scripts/markdown.py, e2e/specs/markdown.spec.ts
Tests for https://github.com/streamlit/streamlit/pull/95
=> Cypress test for escaping html in markdown

.circleci/config.yml
- Capitalize first letter of step names
- Remove period from end of step names
- Rename some confusing job names
@tvst - is there any reason to keep the conda-related logic in this file? Should I remove that as well?
=> Pedantic CircleCI cleanup

examples/bart_vs_bikes.py
Upadate to Bart and Bikes demo as per @treuille request.
=> Bart example update

Makefile, NOTICES, examples/uber.py, frontend/package.json, frontend/src/components/widgets/Slider/Slider.tsx, frontend/src/lib/widgetTheme.ts, frontend/yarn.lock, lib/streamlit/DeltaGenerator.py, proto/streamlit/proto/Slider.proto
https://github.com/streamlit/streamlit-old-private/issues/1100
*Added new field to Slider proto definition:
-string format = 7;
*Overridden ThumbValue and Tick subcomponents from UISlider component
---
---
=> add format option for slider widget and return texts for display values

lib/streamlit/hello.py, scripts/format.sh
**Issue:** #147
**Decription:** New `streamlit hello`. This is a new demo composed by 5 small demos, some of them interactive that the user can choose via a selectbox. Once the user has chosen a demo, she can see the source code and execute the demo.
---
=> New streamlit hello

e2e/specs/selectbox.spec.ts
This may fix selectbox flakiness
=> Adding length check to selectbox e2e test

.github/pull_request_template.md
=> Minor typo in pull_request_template.md

lib/streamlit/DeltaGenerator.py, lib/streamlit/server/Server.py, lib/streamlit/util.py
=> Improve how we serve index.html (for better Windows support)

lib/streamlit/ReportSession.py, lib/streamlit/config.py, lib/streamlit/folder_black_list.py, lib/streamlit/hashing.py
Based on the errors in #242, it looks like our current blacklist won't fix many people's issues. So I expanded it a bit.
I also improved some of our user-facing messages to better explain how to get around st.cache issues
=> Improve st.cache blacklist and user-facing messages

frontend/public/index.html
Issue:
#304 
Description:
Remove page track event after initializing the Segment SDK
=> Don't track page with segment in index.html

docs/troubleshooting.md, frontend/package.json, lib/setup.py, lib/streamlit/hello/demos.py
=> Release 0.48.1

docs/getting_started.md, docs/index.md, docs/main_concepts.md
Getting LP prereq to one line. Adding note to main concepts and get tarted that lets the reader know then can pass both files and URLs to streamlit run as arguments.
---
=> Doc updates

package.json
**Issue:** Useless root package.json
**Description:** Removing file from root
---
=> Removing package json

examples/run_on_save.py
python3 -c "Exception"  # No problems
python3 -c "NotImplementedError"  # No problems
python3 -c "Error"  # NameError: name 'Error' is not defined
[flake8](http://flake8.pycqa.org) testing of https://github.com/streamlit/streamlit on Python 3.8.0
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./lib/tests/streamlit/scriptrunner/test_data/compile_error.py:22:9: E999 SyntaxError: invalid syntax
because i am a compile error!
^
./lib/streamlit/hashing.py:118:32: F821 undefined name 'string_types'
or isinstance(obj, string_types)
^
./lib/streamlit/hashing.py:255:34: F821 undefined name 'string_types'
elif isinstance(obj, string_types):
^
./lib/streamlit/hashing.py:306:42: F821 undefined name 'string_types'
or (isinstance(obj.name, string_types) and …
```
=> Error is an undefined name in run_on_save.py

docs/api-examples-source/widget.time_input.py
[flake8](http://flake8.pycqa.org) testing of https://github.com/streamlit/streamlit on Python 3.8.0
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./lib/tests/streamlit/scriptrunner/test_data/compile_error.py:22:9: E999 SyntaxError: invalid syntax
because i am a compile error!
^
./lib/streamlit/hashing.py:118:32: F821 undefined name 'string_types'
or isinstance(obj, string_types)
^
./lib/streamlit/hashing.py:255:34: F821 undefined name 'string_types'
elif isinstance(obj, string_types):
^
./lib/streamlit/hashing.py:306:42: F821 undefined name 'string_types'
or (isinstance(obj.name, string_types) and os.path.exists(obj.name))
^
./lib/streamlit/hashing.py:394:34: F821 undefined name 'string_types'
if not isinstance(n, string_types) or not n.endswith(".<lambda>") …
```
=> Undefined name: import datetime in widget.time_input.py

docs/conf.py
Fixes: #607
⚠️ **As with most projects, prior to starting to code on a bug fix or feature request, please post in the issue saying you want to volunteer, and then wait for a positive response.** And if there is no issue for it yet, create it first.
This helps make sure (1) two people aren't working on the same thing, (2) this is something Streamlit's maintainers believe should be implemented/fixed, (3) any API, UI, or deeper architectural changes that need to be implemented have been fully thought through by Streamlit's maintainers.
More information in our wiki: https://github.com/streamlit/streamlit/wiki/Contributing
---
**Issue:** Please include a link to the issue you're addressing. If no issue exists, create one first and then link it here.
**Description:** Describe the changes you …
=> Define github_doc_root in docs/conf.py

frontend/package.json, frontend/src/lib/WebsocketConnection.tsx, frontend/yarn.lock, lib/streamlit/server/routes.py
**Issue:** streamlit/streamlit-old-private/issues/1260
**Description:** Replacing XHR with Axios
---
=> Replace fetch with axios in JS websocket code

docs/advanced_concepts.md, docs/api.md, docs/getting_started.md
Fix for https://github.com/streamlit/streamlit/issues/618 (as noted in commit message).
Just fixed some imports in tutorials from mixed **numpy/np/pandas/pd** to unified **np/pd**.
=> fix for #618: pandas and numpy import unification in examples

frontend/src/App.scss, frontend/src/components/core/ReportView/ReportView.scss
**Issue:** Printing via the browser does not seem to work at the moment: only the first page gets printed.
**Description:** This PR fixes #297 
---
=> Fixing print as pdf

lib/streamlit/__init__.py, lib/streamlit/elements/media_proto.py, lib/streamlit/hashing.py
⚠️ **As with most projects, prior to starting to code on a bug fix or feature request, please post in the issue saying you want to volunteer, and then wait for a positive response.** And if there is no issue for it yet, create it first.
This helps make sure (1) two people aren't working on the same thing, (2) this is something Streamlit's maintainers believe should be implemented/fixed, (3) any API, UI, or deeper architectural changes that need to be implemented have been fully thought through by Streamlit's maintainers.
More information in our wiki: https://github.com/streamlit/streamlit/wiki/Contributing
---
**Issue:** Please include a link to the issue you're addressing. If no issue exists, create one first and then link it here.
**Description:** Describe the changes you made to the …
=> Undefined names: missing imports

lib/Pipfile
Issue #540 
Set minimum pandas version
=> pandas.isna was introduced in version 0.21.0

lib/streamlit/hello/hello.py
=> from __future__ imports must occur at the beginning of the file

frontend/src/components/core/Block/Block.tsx, frontend/src/lib/utils.ts
**Issue:** The loading element was showing as a text instead of an info component
**Description:** Updating definition from Proto
---
=> Fixing makeElementWithInfoText

frontend/src/components/widgets/NumberInput/NumberInput.scss
**Issue:** This PR fixes #656 
**Description:** Hiding spin buttons for firefox
---
=> Fixing number input spin buttons for Firefox

Makefile, examples/syntax_error.py, lib/streamlit/caching.py, lib/streamlit/elements/lib/dicttools.py, lib/streamlit/elements/vega_lite.py, lib/streamlit/hello/demos.py, lib/streamlit/type_util.py, lib/tests/streamlit/scriptrunner/test_data/compile_error.py
**Issue:** 
https://github.com/streamlit/streamlit/issues/630
fix errors and add make flake8 command
=> Fix important flake8 errors

lib/streamlit/DeltaGenerator.py, lib/tests/streamlit/delta_generator_test.py
**Issue:**
https://github.com/streamlit/streamlit/issues/678
https://docs.google.com/document/d/1ppFhjmOwux2cnMVAXTKaH4VnClOMu0cVd3apMZv-Yxo/edit?disco=AAAAD89tRbY
=> set new widget_id: key + widget_type

frontend/package.json, frontend/src/lib/format.test.ts, frontend/src/lib/format.ts, frontend/yarn.lock
**Issue:** 
https://github.com/streamlit/streamlit/issues/677
The real problem:
https://github.com/adamwdraper/Numeral-js/issues/512
The solution:
https://github.com/xh/hoist-react/issues/425
=> Update deprecated numeral.js

docs/main_concepts.md, lib/streamlit/DeltaGenerator.py
Addressing issue https://github.com/streamlit/streamlit/issues/518. 
@tvst - How do I get the autofunction API ref to generate into the api.md?
=> Adjusting/improving slider documentation.

docs/api.md
Addresses issue https://github.com/streamlit/streamlit/issues/654
=> Moving media into its own heading in API reference.

lib/streamlit/DeltaGenerator.py
**Issue:** 
https://github.com/streamlit/streamlit/issues/620
Regenerate chart when first data comes.
=> Ticker Saturation on line_chart, bar_chart and area_chart

proto/streamlit/proto/NumberInput.proto
https://github.com/streamlit/streamlit/pull/717#discussion_r352258043
=> Don't reuse numbers for proto fields on number input proto

docs/getting_started.md
⚠️ **As with most projects, prior to starting to code on a bug fix or feature request, please post in the issue saying you want to volunteer, and then wait for a positive response.** And if there is no issue for it yet, create it first.
This helps make sure (1) two people aren't working on the same thing, (2) this is something Streamlit's maintainers believe should be implemented/fixed, (3) any API, UI, or deeper architectural changes that need to be implemented have been fully thought through by Streamlit's maintainers.
More information in our wiki: https://github.com/streamlit/streamlit/wiki/Contributing
---
**Issue:** Please include a link to the issue you're addressing. If no issue exists, create one first and then link it here.
**Description:** Describe the changes you made to the …
=> Fix spelling error for st.progress

frontend/src/App.tsx, frontend/src/components/elements/DeckGlChart/DeckGlChart.tsx, frontend/src/lib/SessionInfo.ts, lib/streamlit/DeltaGenerator.py, lib/streamlit/ReportSession.py, lib/streamlit/config.py, lib/tests/streamlit/config_test.py, proto/streamlit/proto/Initialize.proto
**Issue:** This PR Fixes #781  .
**Description:** Moving mapbox token to a new config option.
---
=> [#781] Moving mapbox token to a new config option

lib/streamlit/__init__.py, lib/tests/streamlit/echo_test.py
=> Fix st.echo with empty lines

lib/streamlit/ReportSession.py, lib/tests/streamlit/ReportSession_test.py
=> Fix runner.installTracer bug that used to freeze Streamlit

frontend/package.json
...caused by "serialize-javascript" package
=> Fix security vulnerability warning

lib/streamlit/DeltaGenerator.py
=> fix string_types check

lib/tests/conftest.py
Don't import any Streamlit modules outside of the mock-config patch context. Some Streamlit modules read config values at import time, which will cause config.toml to be read. We need to ensure that the mock config is read instead of the user's actual config.
Fixes #830
=> Fix conftest.py config mocking

frontend/src/App.test.tsx, frontend/src/components/elements/Alert/Alert.test.tsx, frontend/src/components/elements/BokehChart/BokehChart.test.tsx, frontend/src/components/elements/Json/Json.test.tsx, frontend/src/components/elements/Markdown/Markdown.test.tsx, frontend/src/components/elements/Text/Text.test.tsx, frontend/src/components/widgets/Button/Button.test.tsx, frontend/src/components/widgets/Button/Button.tsx, frontend/src/components/widgets/NumberInput/NumberInput.test.tsx
Adding unit test for Button component, this is an example being used for the new [js unit documentation file](https://docs.google.com/document/d/1tOK_pw1Ae4xfVY97-D0VSpsc8KeQnpb6epiIOlBsEBs/edit#)
---
=> Button component unit test

frontend/src/assets/css/variables.scss, frontend/src/components/widgets/FileUploader/FileUploader.scss, frontend/src/components/widgets/FileUploader/FileUploader.tsx, frontend/src/components/widgets/Slider/Slider.tsx, frontend/src/lib/widgetTheme.ts, lib/streamlit/DeltaGenerator.py, lib/streamlit/ReportSession.py, lib/streamlit/ReportThread.py, lib/streamlit/ScriptRunner.py, lib/streamlit/UploadedFileManager.py, lib/streamlit/server/Server.py, lib/streamlit/string_util.py, lib/tests/streamlit/UploadedFileManager_test.py, lib/tests/testutil.py
This PR hacks together some changes to make the following tweaks to the file uploader UX:
* Make it slightly less tall
* Once a file is uploaded, show the filename in the uploader widget. (I had to do this by showing a div on top of the uploader widget. So nasty :cry: )
* Make the "uploading" and "error" states more compact and just generally nicer-looking.
* Make the drag state nicer-looking, by having the entire widget change to our primary color.
* Make the background color be white when on the sidebar.
This also cleans up the `status` variable, so we can always trust it when making decisions about what to show the user (rather than having to look at both `status` and `errorMessage`)
=> Polish st.file_uploader UX and theme

lib/streamlit/DeltaGenerator.py, lib/tests/streamlit/delta_generator_test.py
=> add_rows support no index column

frontend/src/components/widgets/NumberInput/NumberInput.test.tsx, frontend/src/components/widgets/NumberInput/NumberInput.tsx
**Issue:** This PR fixes https://github.com/streamlit/streamlit/issues/867
**Description:** min and max was not working
---
=> Fixing min max behavior for NumberInput

docs/api.md, docs/main_concepts.md
⚠️ **As with most projects, prior to starting to code on a bug fix or feature request, please post in the issue saying you want to volunteer, and then wait for a positive response.** And if there is no issue for it yet, create it first.
This helps make sure (1) two people aren't working on the same thing, (2) this is something Streamlit's maintainers believe should be implemented/fixed, (3) any API, UI, or deeper architectural changes that need to be implemented have been fully thought through by Streamlit's maintainers.
More information in our wiki: https://github.com/streamlit/streamlit/wiki/Contributing
---
**Issue:** Please include a link to the issue you're addressing. If no issue exists, create one first and then link it here.
**Description:** Describe the changes you made to the …
=> Fix doc selectbox

docs/main_concepts.md
=> Fix documentation typos

lib/tests/streamlit/hashing_test.py
The python import was wrong. I'm confused why this hasn't blown up till now...
=> Fix CodeHashingTest.test_external_module

lib/streamlit/bootstrap.py
**Issue:** This PR fixes #988 .
**Description:** Forcing environment variable from python
---
=> Forcing MAPBOX_API_KEY environment variable

lib/streamlit/DeltaGenerator.py, lib/tests/streamlit/radio_test.py, lib/tests/streamlit/selectbox_test.py
**Issue:** This PR fixes #982 
**Description:** Using NoValue instead of None
---
=> Fixing return None for Radio and Selectbox

docs/changelog.md, docs/index.md, docs/troubleshooting/common-issues.md, frontend/package.json, lib/setup.py
Streamlit 0.54.0 + Screencasting feature (which was hidden in the previous release)
=> Release 0.55.0

lib/streamlit/DeltaGenerator.py
Update the st.progress doc example. 
---
**Issue:** https://github.com/streamlit/streamlit/issues/1048
**Description:**: Sleep for 0.1 second for progress bar 1%. So user can see the progress bar animation
---
=> Update the st.progress doc example

lib/streamlit/caching.py, lib/streamlit/hashing.py
I pushed https://github.com/streamlit/streamlit/pull/1089/files too soon, forgot to fix @jrhone's comment
=> Fix missing caching URL

frontend/package.json, frontend/yarn.lock
=> Update plotly.js to 1.52

frontend/src/hocs/withMapboxToken/MapboxToken.test.ts, frontend/src/lib/FileUploadClient.test.ts
Fixes frontend test failures introduced by my last merge to develop
=> Fix frontend test failures

lib/streamlit/DeltaGenerator.py
**Issue:** Fixes streamlit/streamlit-old-private/issues/425.
**Description:** Updating examples using `use_container_width` param
---
=> Fixing examples on mobile

frontend/package.json, frontend/yarn.lock
**Issue:** Fixes #1009 .
**Description:** Upgrading vega and vega-lite
---
=> Upgrading vega and vega-lite

frontend/src/components/elements/PlotlyChart/PlotlyChart.tsx
**Issue:** Closes #1154 
**Description:** Adding a key in order to force the re-render of Plot Component
---
=> #1154 | Plotly fullscreen bug

e2e/specs/st_reuse_label.spec.ts, frontend/package.json, frontend/src/components/elements/BokehChart/BokehChart.test.tsx, frontend/src/components/elements/BokehChart/BokehChart.tsx, frontend/yarn.lock
**Issue:** This fixes #1134
**Description:**  BokehChart was not working
---
=> Fixing BokehChart

e2e/scripts/st_reuse_label.py, lib/streamlit/ReportSession.py, lib/streamlit/server/Server.py, lib/tests/streamlit/ReportSession_test.py
=> Fix bug where script was executing twice on first run.

lib/streamlit/hashing.py, lib/tests/streamlit/hashing_test.py
=> hash_func for tensorflow session

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/doc_improvement.md, .github/ISSUE_TEMPLATE/feature_request.md
- Adding `needs triage` label to our templates
- Blocking new issues without any template
- Adding our community link
- Adding our documentation link
=> GH Templates

frontend/package.json, frontend/yarn.lock
Fixes a security vulnerability.
=> Bump jquery to ^3.5.0
