streamlit/streamlit

- lib/streamlit/caching.py
- lib/streamlit/hashing.py
This fixes an uncaught Python 2 exception, as reported here: #1230.
It also hides a hashing warning when a user imports a module from inside a cached function. This is a common scenario, and the warning UI is too invasive today. We should come up with a better UI.
> Fix #1230: OSError not caught when writing cache to disk

- frontend/src/components/core/Block/Block.tsx
- frontend/src/components/elements/DataFrame/DataFrame.tsx
- frontend/src/lib/DeltaParser.ts
- lib/streamlit/DeltaGenerator.py
- lib/tests/streamlit/dataframe_dimensions_test.py
- lib/tests/streamlit/help_test.py
- proto/streamlit/proto/ForwardMsg.proto
This PR proposes to add a width and height parameter to st.dataframe. Protobuf is changed to include an ElementDimensionSpec field to carry this information. This is included as part of the forward message metadata. The message is parsed and height/width information is extracted and passed down to the Dataframe React component in Block.tsx. Width is set in Block.tsx since existing logic applies to a generic element, while height is set in the Dataframe element in some ad hoc logic.
> Adding width and height parameter to st.dataframe

- frontend/src/lib/WebsocketConnection.tsx
1. Moved `onreadystatechange`  logics to `onload` event as these two events were overlapping between.
2. Removed unused events
> Fix WebsocketConnection totalTries count

- frontend/src/lib/MetricsManager.ts
- lib/streamlit/credentials.py
- lib/tests/streamlit/credentials_test.py
- Nicer `streamlit activate` prompt and text from @tvst
- Remove the unused "activation code" stuff from Credentials.
- Credentials: email is now optional. If the user doesn't enter one, it will be stored as the empty string. The client will omit the "authoremail" trait from the Segment.io identifier if the user didn't enter an email.
Fixes #63
> Email, metrics prompt

- lib/streamlit/__init__.py
This is a fix for https://github.com/streamlit/streamlit/issues/53
As we said, we will leave the issue open until we have confidence the bug is not showing up anymore
> Fix bug where message is not initialized in the spinner code

- frontend/src/index.jsx
Set z-index of BaseUI component layers to the z-index of Vega Lite popups
> Sidebar z-index bug

- lib/Pipfile
- lib/streamlit/cli.py
- lib/tests/streamlit/cli_test.py
We want to support `streamlit run <url>`
This PR adds support for this usage of the `run` command. 
- Added logic to recognize a url - we use `validators.url` for this. `http://somethign` is a url. `something` is not
- Moved file validation from click to custom logic, since the first argument of `run` is now overloaded and can be file or url
- Added cli unit tests
> Adding `streamlit run` by url

- lib/streamlit/hashing.py
- lib/tests/streamlit/hashing_test.py
> Fix hashing if the object has a name but the name is not a string.

- docs/index.md
@tvst + @kellyamanda - This PR covers two things: 
* Updates to the Landing Page per Amanda's doc
* Updates to the Support section of the sidebar
* Added link to GitHub
* Added link to Community forum
* Removed Slack
* Do we want to rename the interactive report tutorial. If yes, we should update the filename as well. 
* I know that we want to change report to app throughout the docs. I did a global search on the repo, this also contains references in code and the API reference, but there are ~986 instances of the word report. How do we want to address this? It's not going to be as easy as a global find and replace. Should we start by targeting the docs? Maybe: 
* P0 - Documentation (Concepts)
* P1 - API Ref
* P2 - Code comments
> Updates to LP and sidebar

- lib/streamlit/bootstrap.py
Fixed bug that hinders the startup under windows by using platform specific SIGQUIT signal.
[x] By checking this box, I agree that all contributions to this project are made under the Apache 2.0 license.
> Fix bug for startup under windows

- examples/magic.py
- lib/streamlit/magic.py
- lib/tests/streamlit/magic_test.py
- Magic supports `while`, `async with`, `async for` statements, and async functions
- Ignore `yield` and `yield from` statements (these were previously being magicked, which resulted in random-seeming "None" values being st.written to the report).
- I also created an `examples/magic.py` file for easy visual testing of these things, which I used while debugging. (The magic unit tests also verify these fixes.)
Fixes #135
> Magic fixes

- Makefile
- scripts/format.sh
Some quality of life improvements for code formatting.
- Added new make rules `make pyformat` and `make jsformat`, which run Black/Prettier on all source files. (These aren't used in any precommit hooks or CircleCI jobs, but I've found myself wanting to run the commands manually sometimes.)
- `scripts/format.sh` no longer tries to format deleted Python files (previously, if you had a deleted file in staged files, format.sh would fail).
> Black, Prettier fixes

- lib/streamlit/server/Server.py
- lib/tests/streamlit/Server_test.py
When running `streamlit` it starts up the server listening to `server.port`, in case the user has not set the port explicitly the server will add 1 to the port number and try to run the server in that port, in order to be able to have several `streamlit` projects running simultaneously.
Please review if the message set in `_set_option` third parameter is appropriate.
Please advise if you think there should be tests for this and what to test.
to test locally with `make all-devel` make sure to have the following settings
```
developmentMode=false
useNode=false
```
After having those config keys set up just run `streamlit hello` in more than one terminals and see the report pop up in the browser over a different port.
resolves #116
> Rotate server port if current one is taken

- frontend/src/components/elements/Text/Text.tsx
**Issue:** #151
**Decription:** Reverting lost changes
> Stop react-markdown from converting "[foo]" to a link

- lib/streamlit/credentials.py
- lib/tests/streamlit/credentials_test.py
**Issue:**
#175 
- Fix credentials reset by only initializing credentials singleton once
---
> Fix login flow crashes for an invalid Credentials.toml file

- examples/empty_charts.py
- lib/Pipfile
- lib/Pipfile.locks/python-2.7.16
- lib/streamlit/bootstrap.py
- lib/tests/streamlit/bootstrap_test.py
- scripts/run_bare_integration_tests.py
Fixes #177, but in a way that makes @tvst sad :)
I wrote longer notes in the issue (#177) about what needs to happen to avoid importing `matplotlib` here - but the tl;dr is that `bootstrap.run` is called after matplotlib is indirectly imported elsewhere. Since matplotlib only reads MPLBACKEND on import, bootstrap gets there too late to have its environment variable override have any effect.
> Fix Matplotlib crash on OS X

- lib/streamlit/hello.py
- scripts/format.sh
- Mostly, this was my final pass on `hello.py`.
- This does fix #208 
- Added text to `intro()` which the user sees first when they type `streamlit hello`.
- Downloading an displaying [an image](https://streamlit-demo-data.s3-us-west-2.amazonaws.com/hello-welcome.png) on the landing page for `streamlit hello`
- Added more comments
- Replaced `matplotlib` with `altair`
- Removed a hack I added to suppress black formatting.
- Instead, now using `# fmt: off` as [suggested by Henrikh](https://streamlit.slack.com/archives/C9FJJN8Q7/p1569541419014700)
- Changed the demo order
- Replaced @monchier's homespun `reset_indentation` with `textwrap.dedent` 
---
> Added intro text to hello.py

- lib/streamlit/hello.py
Changing the way we initialize the OrderedDict in `hello.py`. I now use an iterable which should maintain the the order with Python2.7
> OrderedDict should maintain the order of the keys

- lib/streamlit/hashing.py
As the title says. Small fix to error message. We were suggesting a non-existing option.
> ignore_cache should be ignore_hash in error message

- frontend/src/assets/css/theme.scss
https://github.com/streamlit/streamlit/issues/161
Decription:
Interacting with widgets sometimes changes the vertical scroll position. This shouldn't be the case.
The problem was when styletron auto generated class h1 (or h2, h3, h4, h5 ,h6) was implemented, has a conflict with bootstrap .h* class.
To reproduce it, just run "streamlit run examples/interactive widgets.py" and change the slider value until to see the slider height changing
---
> Unset all bootstrap H* clases

- lib/streamlit/hello.py
Catch urllib errors in mapping_demo. (To test the fix, run `streamlit hello` with no internet access.)
There are two bugs in the associated issue, but the other one - the missing `urllib` import - was fixed in some other commit.
Fixes #222
> Fix `streamlit hello` error

- docs/getting_started.md
Fixed Value error when running the progress bar example in docs/getting_started.
I also add f-string to show that streamlit support f-strings. 
Fixes : [#234 ](https://github.com/streamlit/streamlit/issues/234)
> Fixed Error in Show progress  docs/getting_started.md error #234

- docs/main_concepts.md
**Issue:** https://github.com/streamlit/streamlit/issues/266
**Decription:**
In the [Main Concepts](https://streamlit.io/docs/main_concepts.html) part of documentation, there is a sample code, which gives error when copied and ran directly. The issue was due to presence of wrong quote. I have updated the doc to the correct quote.
---
> Fix wrong quote used in the provided sample code

- Makefile
**Issue:**
#68 
- Write `make jslint` output to a file only when running in CircleCI
> different jslint commands for circleci and not

- e2e/scripts/code.py
- frontend/src/components/elements/CodeBlock/CodeBlock.tsx
**Issue:** 
#146 
- Don't pass empty strings to Prism.highlight
> Fix for st.code("") raising an exception in the browser

- lib/streamlit/credentials.py
- lib/tests/streamlit/credentials_test.py
**Issue:** #203 
**Description:** Skipping the credentials dialog while headless mode is setted up, 
---
> #203 Skipping credentials in headless mode

- frontend/src/components/elements/Text/Text.tsx
It looks like syntax hiliting was broken at https://github.com/streamlit/streamlit/commit/98ac69d180313eab7d3d1dee4bb24744247d3948
@arraydude: I'm assuming that `renderers` was removed by mistake, but if not (because it doesn't play nicely with the HTML fixes you made), we should come up with a solution that allows syntax hiliting in markdown code blocks.
> Fix syntax hiliting

- frontend/src/App.test.tsx
- frontend/src/App.tsx
- frontend/src/lib/DeltaParser.ts
- frontend/src/lib/WidgetStateManager.ts
- frontend/src/lib/utils.test.ts
- frontend/src/lib/utils.ts
**Issue:** https://github.com/streamlit/streamlit/issues/218
**Description:** Widget old state was not cleaned up and caused old values to be returned to the user. This PR add some logic to clean up the state of widget that are not currently shown on the page. Widget that are shown on the page are not cleaned up.
---
> Clean up old widget state after a run

- docs/tutorial/create_a_data_explorer_app.md
Remove "Share Data" section from "Create a Data Explorer" tutorial.
**Issue:** #334 .
**Description:** I've removed the section related to the "Share App" feature. I've rephrased the following section to make the flow "more natural".
---
> Remove "Share Data" from tutorial. Fix #334

- lib/streamlit/hello/demos.py
- lib/streamlit/hello/hello.py
To help debug errors like [this one](https://discuss.streamlit.io/t/connection-error-this-demo-requires-internet-access/370), this PR shows the exception message when `urllib` fails in `hello.py`.
Also: I just noticed that in `develop` the demo descriptions for `hello.py` are all shuffled. So I fixed that here too.
> Show error message when urllib fails in hello.py

- frontend/src/components/elements/Audio/Audio.tsx
- frontend/src/components/elements/Video/Video.tsx
- lib/streamlit/DeltaGenerator.py
- lib/tests/streamlit/help_test.py
- lib/tests/streamlit/streamlit_test.py
- proto/streamlit/proto/Audio.proto
- proto/streamlit/proto/Video.proto
Resolving https://github.com/streamlit/streamlit/issues/372
Set audio/video start position, just with current_time argument to st.audio()/st.video() function.
> Add ability to set audio/video start position

- lib/streamlit/DeltaGenerator.py
- lib/streamlit/ReportThread.py
- lib/streamlit/__init__.py
- lib/streamlit/errors.py
- lib/tests/streamlit/delta_generator_test.py
- lib/tests/testutil.py
- When two widgets with the same ID are encountered in a report run, we throw a DuplicateWidgetID exception. The exception tells the user that they can use the new optional "key" parameter that each widget now takes in order to fix the issue.
- (The error is slightly different if the user has manually supplied an identical key to multiple widgets.)
- To track widget keys, `ReportContext` has a new `widget_ids_this_run` set. Each time a widget has an ID assigned, we add that ID to the set. If the ID was already in the set, the exception is thrown. (Because it's possible to access this set from multiple threads, access to it is wrapped in a `threading.Lock`).
- `ScriptRunner` clears the `widget_ids_this_run` right before running its script.
- User-supplied widget keys are "namespaced" by …
> Widgets with identical IDs raise an Exception

- lib/streamlit/DeltaGenerator.py
- lib/streamlit/__init__.py
- lib/tests/streamlit/streamlit_test.py
`st._text_exception` is a private function that's not used anywhere, and isn't intended to be used by user code. So now it's gone!
> st._text_exception isn't used anywhere. Remove it!

- frontend/src/App.test.tsx
- frontend/src/components/elements/GraphVizChart/GraphVizChart.tsx
- lib/streamlit/hello/demos.py
- lib/streamlit/watcher/LocalSourcesWatcher.py
- lib/tests/streamlit/watcher/LocalSourcesWatcher_test.py
See: https://discuss.streamlit.io/t/issue-in-running-streamlit-app-in-anaconda-environment/380
This fixes the error in the post, but I think there's a deeper issue at hand: why does the user have no permission to read a file that Streamlit wants to read?
My guess is the temporary file we save the URL to is stored in a common `tmp` folder that contains things the user has no access to. Should we create a subfolder in `tmp` and put the file in there, to avoid this problem? @monchier 
- If so, then let's do that in another PR
> Don't watch files the user has no permission to read

- lib/streamlit/caching.py
- lib/streamlit/hashing.py
- lib/tests/streamlit/caching_test.py
- lib/tests/streamlit/help_test.py
**Issue:**
#412 
- Rename `ignore_hash` to `allow_output_mutation`
- Help users migrate to the new name by throwing an error if `ignore_hash` is used
- Only added to `@st.cache` and not `class Cache` since only the decorator is exposed to the user right now
> Rename ignore_hash to allow_output_mutation

- lib/streamlit/ScriptRunner.py
- lib/streamlit/__init__.py
- lib/streamlit/caching.py
- lib/streamlit/config.py
- lib/streamlit/elements/exception_proto.py
- lib/streamlit/source_util.py
- lib/tests/streamlit/scriptrunner/ScriptRunner_test.py
- lib/tests/streamlit/scriptrunner/test_data/good_script_latin_encoding.py
- lib/tests/streamlit/scriptrunner/test_data/good_script_no_encoding.py
To solve #399 we need to specify the encoding as UTF8 when reading the user's script. So you'd think this is all we need to do:
```
open(the_file, encoding='utf-8')
```
But this doesn't always work because:
1) The `encoding` kwarg doesn't exist in Python 2
2) If we pass the `encoding` arg and it doesn't match whatever the user's script specifies (via [PEP263](https://www.python.org/dev/peps/pep-0263/) headers), Python raises a SyntaxError
For (2), we have to use the `tokenize` module's `open()` function, which respects PEP263 and defaults to UTF8.
But `tokenize.open()` doesn't exist in Python 2. So we need to provide a fallback in that case. The fallback is Streamlit's old behavior, where bug #399 exists.
---
In the process of writing this PR I noticed that some SyntaxErrors don't show up …
> Specify encoding when reading the user's script. Fixes #399

- docs/cli.md
As noted in https://github.com/streamlit/streamlit/issues/337, `streamlit run` only accepts bare arguments for arguments intended for the user script. This is currently not reflected in the documentation and could be confusing for users trying to make use of this feature.
**Issue:** https://github.com/streamlit/streamlit/issues/337
**Description:** Hi! This is just a super quick PR for a documentation update. A couple weeks back I was trying to get my script to accept custom args and couldn't figure it out from the docs. I created a PR to add some language around how custom args should be passed to a user script. Please feel free to change/suggest changes to the language if there is another way you'd prefer to explain this.
---
By submiting this pull …
> Update cli.md to reflect correct way of passing custom args

- docs/conf.py
- e2e/scripts/sidebar.py
- e2e/scripts/vega_lite_chart.py
- frontend/src/lib/ConnectionManager.ts
- frontend/src/lib/ForwardMessageCache.test.ts
- frontend/src/lib/UriUtil.test.ts
- frontend/src/lib/UriUtil.ts
- lib/streamlit/DeltaGenerator.py
- lib/streamlit/Report.py
- lib/streamlit/ReportSession.py
- lib/streamlit/config.py
- lib/streamlit/hello/demos.py
- lib/streamlit/server/Server.py
- lib/streamlit/server/routes.py
- lib/streamlit/server/server_util.py
- lib/streamlit/version.py
- lib/tests/streamlit/Report_test.py
- lib/tests/streamlit/Server_test.py
- lib/tests/streamlit/bootstrap_test.py
- lib/tests/streamlit/config_test.py
- lib/tests/streamlit/help_test.py
- lib/tests/streamlit/version_test.py
- proto/streamlit/proto/StaticManifest.proto
Fixes #225 
Adds the config option config.baseUrlPath. When set to a value like 'foo', Streamlit will be served from 'hostname:port/foo'.
> Implement config.baseUrlPath

- frontend/yarn.lock
For some reason, `yarn upgrade` breaks the date picker.
See screenshot:
As a solution, I rolled back #436 and rolled it forward by doing `yarn add foo` for each package we actually wanted to upgrade. This makes sure nothing else upgrades behind out backs.
> Roll back yarn.lock to fix bug where date picker was at wrong place.

- lib/streamlit/server/server_util.py
**Issue:** #521 
**Description:** When constructing Tornado routes, strip any forward-slash characters on the value of server.baseUrlPath. Otherwise, routes with double slashes are generated, making them not match anything.
The Report class already strips slashes when generating URLs, so the URLs printed to the console don't look any different.
Given an invocation like `streamlit run --server.baseUrlPath /abc sa/gui.py`, here's the routes being generated.
```
[
('^//abc/stream/?$', …), 
('^//abc/healthz/?$', …), 
('^//abc/debugz/?$', …), 
('^//abc/metrics/?$', …), 
('^//abc/message/?$', …), 
('^//abc/(.*)/?$', …)
]
```
Stripping slashes gives the correct route.
```
[
('^/abc/stream/?$', …), 
('^/abc/healthz/?$', …), 
('^/abc/debugz/?$', …), 
('^/abc/metrics/?$', …), 
('^/abc/message/?$', …
```
> Strip slashes around baseUrlPath value

- docs/cli.md
- lib/streamlit/cli.py
**Issue:** #476 
**Description:** Set auto_envvar_prefix to STREAMLIT to accept parameters from environment variables in addition to regular CLI arguments. This is a Click option that will automatically get values from  env vars if available.
> Set auto_envvar_prefix to STREAMLIT

- lib/streamlit/server/Server.py
- lib/streamlit/server/routes.py
- lib/streamlit/server/server_util.py
- lib/tests/streamlit/Report_test.py
**Issue:** #525 
**Description:** The report urls don't show a trailing slash. This works when Streamlit is running at the base URL because browsers will implicitly add a `/` for a request on the root. But, this does not work when a custom `server.baseUrlPath` is defined, resulting in a 404 Not Found.
This PR adds a redirect from no trailing slash to with trailing slash. And, it also adds a trailing slash to the report URL so that the correct path is shown to users.
**Before:**
```
root@672e90be303e:/project# streamlit run --server.baseUrlPath abc sa/gui.py
You can now view your Streamlit app in your browser.
Network URL: http://172.17.0.2:8501/abc
External URL: http://209.89.162.170:8501/abc
```
```
‣ ~ http -h http://127.0.0.1:8501/abc 
HTTP/1.1 404 Not Found
‣ ~ http -h …
```
> Handle lack of trailing slash

- lib/streamlit/cli.py
- lib/streamlit/temporary_directory.py
- lib/streamlit/temporary_file.py
- lib/tests/streamlit/cli_test.py
- lib/tests/streamlit/temporary_directory_test.py
- lib/tests/streamlit/temporary_file_test.py
**Issue:** https://github.com/streamlit/streamlit/issues/301
**Description:** In Windows, we cannot rely on NamedTemporaryFile removing the temporary file that we use for the temporary python script on running from url. This PR adds a custom `TemporaryDirectory` context manager to use with remote files.
The `TemporaryDirectory` context manager remove the content of the temporary directory when exits.
---
> Use custom context manager for temporary file in cli.py

- lib/streamlit/watcher/LocalSourcesWatcher.py
- lib/tests/streamlit/watcher/LocalSourcesWatcher_test.py
- lib/tests/streamlit/watcher/test_data/nested_module_child.py
- lib/tests/streamlit/watcher/test_data/nested_module_parent.py
**Issue:** https://github.com/streamlit/streamlit/issues/366
This is a sketch for now, we may want to look at a more sophisticated fix. Although it does fix the linked issue, it does so in a somewhat scorched-earth manner.
Essentially what is happening is that if you have a module which is not directly imported by the base module (e.g.` app.py` imports `a.py`, `a.py` imports `b.py`), then changes to that module will not be reloaded when a file change is detected.
As far as I can understand, this is what is happening:
- User changes `b.py`
- Reload logic:
- Deletes `b` from `sys.modules`
- Calls eval on the code from `app.py`
- The code in `app.py` imports `a`, which is already present in `sys.modules`, and so we are done
- The result is that we keep using the old copy of …
> Workaround for deep import reloads not working

- lib/streamlit/DeltaGenerator.py
- lib/streamlit/util.py
- lib/tests/streamlit/delta_generator_test.py
We forgot to add the key parameter to the `text_input` widget. This PR adds the parameter and update the related test.
> Adding missing key parameter to text_input

- Makefile
**Issue:** https://github.com/streamlit/streamlit/issues/555
The Makefile uses bash-isms like `[[ $(PY_VERSION) == "3.6.0" || $(PY_VERSION) > "3.6.0" ]]`
that don't work in POSIX sh.  So let's be explicit.
This fixes a problem with the build in Ubuntu, where you currently get `[[: not found`.
> Explicitly use bash in Makefile

- examples/bart_vs_bikes.py
Issue [558](https://github.com/streamlit/streamlit/issues/558)
fixing bart_vs_bikes.py example, url is now properly defined regardless of the OS.
> #558 fix bart_vs_bikes example

- lib/streamlit/bootstrap.py
- lib/tests/streamlit/bootstrap_test.py
Issue #469 
The docstring for `def _fix_matplotlib_crash():` says it's OS-independent but in the code we were restricting the fix to Mac only
```
This fix is OS-independent. We didn't see a good reason to make this
Mac-only. Consistency within Streamlit seemed more important.
```
> Fix Matplotlib backend on all platforms

- frontend/src/components/elements/PlotlyChart/PlotlyChart.tsx
Plotly charts are not always re-rendering properly, per #512.
This seems to be a react-plotly bug; I made a standalone repro case and
submitted it to them here https://github.com/plotly/react-plotly.js/issues/167.
Fixes #512
(To test this fix, you can run the test code from #512.)
> PlotlyChart: Force recreation of <Plot> in render

- frontend/src/App.tsx
**Issue:** This PR Fixes streamlit/streamlit-old-private/issues/919
**Description:** Cleaning elements lists when the reportHash changes in order to clean old stale elements from a different report.
---
> Cleaning stale elements when the reportHash changes

- lib/setup.py
Issue #283 
Check if we can run `gcc` before making watchdog a requirement.
Todo:
Verify that `gcc --version` returns a failure exit code if `xcrun` can't be found
> Only install watchdog on Mac if gcc is working

- frontend/src/components/widgets/TextArea/TextArea.tsx
**Issue:** This PR fixes #696 
**Description:** Enter key has different keyCode depending on browser and OS
---
> Fixing CTRL+ENTER on Windows

- e2e/Dockerfile
Dockerfile: install the specific version of node that we expect
Our e2e/Dockerfile currently fails to find `yarn`, because it's installing a different version of node than expected.
> Fix e2e/Dockerfile

- lib/streamlit/elements/altair.py
**Issue:**
https://github.com/streamlit/streamlit/issues/691
This fix the issue for line_chart, bar_chart and area_chart.
```
import streamlit as st
import pandas as pd
data = pd.DataFrame({
'index': ['Cincinnati', 'San Francisco', 'Pittsburgh'],
'sports_teams': [6, 8, 9],
}).set_index('index')
st.write(data.index.name)
st.write(data)
st.bar_chart(data)
data = pd.DataFrame({
'city': ['Cincinnati', 'San Francisco', 'Pittsburgh'],
'sports_teams': [6, 8, 9],
}).set_index('city')
st.write(data.index.name)
st.write(data)
st.bar_chart(data)
```
> st.bar_chart should work with indices with names besides "index"

- frontend/src/components/elements/DeckGlChart/DeckGlChart.tsx
- lib/streamlit/DeltaGenerator.py
Issue https://github.com/streamlit/streamlit-old-private/issues/964
- Add support for getColor and getTargetColor with custom column getters, using getColorR/G/B/A and getTargetColorR/G/B/A for DeckGL Charts.
- Update DeckGL Chart documentation.
```
Connect specific fields in the dataset to properties of the chart. 
The exact keys that are accepted depend on the "type" field.
For example, Deck.GL"s documentation for ScatterplotLayer
shows you can use a "getRadius" field to individually set
the radius of each circle in the plot. So here you would
set "getRadius": "my_column" where "my_column" is the name
of the column containing the radius data.
For things like "getColor", which expect an array rather
than a scalar value, we provide alternates that make the
API simpler to use with …
```
> Add support for getColorX and getTargetColorX to DeckGL Chart

- lib/streamlit/__init__.py
**Issue:**
https://github.com/streamlit/streamlit/issues/715
Try to use the `machine-id` (if exist) to generate the `__instalation_id__`. If not, keep using `uuid.getnode()`
> Improve __instalation_id__ generation

- lib/streamlit/DeltaGenerator.py
- lib/tests/streamlit/delta_generator_test.py
Turns out the original commit broke the case where one widget depends on the output from another:
```py
country = st.selectbox("Country", countries)
states = country_state_map[country]
state = st.selectbox("State", states)
```
> Roll back widget_id (commit 0577857)

- lib/streamlit/DeltaGenerator.py
**Issue:** Fixes #659 
**Description:** `radio()` and `date_input()` example strings were broken
---
> Fixing broken example strings for radio() and date_input()

- frontend/src/lib/ConnectionManager.ts
- frontend/src/lib/WebsocketConnection.tsx
Currently, if there's some sort of fatal error in WebsocketConnection, it hangs and doesn't display anything meaningful to the user. These changes fix that:
- The "CONNECTION_WTF" event is now called "FATAL_ERROR", and is properly handled. 
- If we receive this event from any FSM state, we transition to the "DISCONNECTED_FOREVER" state and send along an error message to ConnectionManager.
- These error messages are now displayed in the "Connection Error" dialog. (Previously, the dialog would just say "Unknown".)
Fixes #26
> WebsocketConnection: handle fatal errors

- e2e/scripts/empty.py
- lib/streamlit/__init__.py
- lib/streamlit/bootstrap.py
- lib/streamlit/elements/lib/dicttools.py
- lib/streamlit/elements/vega_lite.py
- lib/streamlit/type_util.py
- lib/tests/streamlit/multiselect_test.py
I ran `make pyformat` to fix black violations that are causing CircleCI builds to fail
> Fix pylint errors

- lib/streamlit/cli.py
- lib/tests/streamlit/cli_test.py
**Issue:** Fixes #671 
**Description:** Warn users when they try to run Streamlit on a not allowed file extension.
---
> Checking allowed file extensions

- lib/streamlit/config.py
- lib/tests/conftest.py
- lib/tests/streamlit/bootstrap_test.py
- lib/tests/streamlit/config_test.py
- lib/tests/streamlit/streamlit_test.py
This fixes a handful of python tests that fail on Mac. It also cleans up some `matplotlib` backend testing bits that could result in non-deterministic failures.
- `test_fix_matplotlib_crash`: don't use "tkagg" backend, because it can fail to load on Mac depending on how the Python interpreter was built. (This doesn't work on my machine, for example, using a Python from pyenv).
- fix the "headless" config test on Mac (this was broken by the recent `env_util` addition).
- for various matplotlib tests, use `plt.switch_backend` if the backend isn't what we want.
> Fix Python tests on Mac

- frontend/src/components/widgets/NumberInput/NumberInput.test.tsx
- frontend/src/components/widgets/NumberInput/NumberInput.tsx
- lib/streamlit/DeltaGenerator.py
1. Fixes `NumberInput` so that it doesn't explode on malformed format strings. `sprintf` throws an exception if the format string is bad, and we're currently not handling this, so a bad format string will just crash the Streamlit page.
2. Clarify the `DeltaGenerator.number_input` format doc a bit.
The frontend uses `sprintf`, which does not really support Python-style format strings, so I removed that bit of text.
(sprintf _does_ support named parameters, but the user has no control over the params that get passed to the sprintf function (there's only one param, and it's the value of the number input),
so this distinction is not meaningful here.)
> NumberInput format string fixes

- lib/streamlit/config.py
- lib/tests/streamlit/config_test.py
If `s3.url` is set in the user's config, ensure that it's an absolute URL.
An absolute URL starts with either `scheme://` or `//` -- if the configured URL does not start with either prefix, prepend it with `//` to make it absolute. (If we don't do this, and the user enters something like `url=myhost.com/reports`, the browser will assume this is a relative URL, and will prepend the hostname of the Streamlit instance to the configured URL.)
Fixes #802
> Ensure that s3.url is an absolute URL

- lib/streamlit/caching.py
- lib/tests/streamlit/caching_test.py
Issue #790 
Remove the second hashing of the input and the input mutation warning.
Don't store `args_mutated` in the cache
> Remove cache input mutation check

- lib/streamlit/DeltaGenerator.py
- lib/streamlit/ReportSession.py
- lib/streamlit/ReportThread.py
- lib/streamlit/ScriptRunner.py
- lib/streamlit/UploadedFileManager.py
- lib/streamlit/server/Server.py
- lib/streamlit/string_util.py
- lib/tests/streamlit/UploadedFileManager_test.py
- lib/tests/testutil.py
This does two things:
* Changes the return value of `st.file_uploader`.
* When `encoding` is `None`, returns `BytesIO`
* When `encoding` is set to a valid encoding or its unset (i.e. set to `"auto"`), returns `StringIO`
* When no file has been selected, returns `None`
* Renames `FileManager` to `UploadedFileManager`
The nice thing about `BytesIO` and `StringIO` is that they act exactly like files!
> Fix st.file_uploader return value

- lib/tests/streamlit/add_rows_test.py
Add tests to cases when the dataframe have not a `index` column. 
Add tests to cases when the chart was created without data.
> Add new tests for add_rows method  with set_index in dataframes

- frontend/package.json
As we are needing to have a well tested code i'm adding a new script to our package.json which creates a code coverage report in order to have better insights of how we are doing our tests.
Scripts:
- `yarn test:coverage`: if you want to generate a report for the complete frontend project
- `yarn test src/components/elements/Alert/Alert.test.tsx --coverage`: If you need to check the coverage for an specific file
The report will be created in `/frontend/coverage/index.html`
---
> test:coverage script

- lib/streamlit/file_util.py
- lib/streamlit/hashing.py
- lib/streamlit/watcher/LocalSourcesWatcher.py
- lib/tests/streamlit/file_util_test.py
- lib/tests/streamlit/watcher/LocalSourcesWatcher_test.py
We currently limit the modules we watch to modules contained in the current directory. This PR extends the watched modules to modules contained in the `PYTHONPATH` as well. For consistency, we also enable hashing for the same modules in the `PYTHONPATH`.
**Issue:** https://github.com/streamlit/streamlit/issues/805
> Add modules in PYTHONPATH to watched modules

- .circleci/config.yml
- e2e/Dockerfile
- e2e/specs/hello.spec.ts
- frontend/src/lib/SessionInfo.ts
- scripts/run_e2e_tests.sh
Fixes #879 
The issue only happens when when you have:
* `server.headless = true`
_and_
* no email set
(Note that headless is also turned on automatically when we detect that there's no display — such as when you're running in Docker)
This caused a null check to fail because the null check wasn't actually checking `null`. Instead it was checking `falsy`, and an empty email (an empty string) is falsy.
> Fix #875: frontend error saying "Bad message format - Tried to use SessionInfo before it was initialized"

- proto/streamlit/proto/Element.proto
- proto/streamlit/proto/NumberInput.proto
Use the `reserved` keyword for field numbers that shouldn't be re-used. The proto compiler will enforce this.
> Protobuf: use "reserved" keyword

- README.md
fix URL from "forteams" to "for-teams"
> fix broken url for "Streamlit for teams"

- frontend/src/components/widgets/TextInput/TextInput.test.tsx
- frontend/src/components/widgets/TextInput/TextInput.tsx
- lib/streamlit/DeltaGenerator.py
- lib/tests/streamlit/text_input_test.py
- proto/streamlit/proto/TextInput.proto
`st.text_input` takes a new optional parameter, "type". Valid values are "default" (which is used if no value is specified) and "password".
The password text_input works as you'd expect, masking user typing!
Fixes #420
> st.text_input: password support

- lib/streamlit/DeltaGenerator.py
**Issue:** #895 
**Description:** We were showing a wrong supported emoji list. Updating with the one that is being used by https://github.com/omnidan/node-emoji
---
> Updating emoji docstring for markdown

- frontend/src/hocs/withScreencast/components/VideoRecordedDialog/VideoRecordedDialog.tsx
**Issue:** Emojis should be wrapped in `<span>`, have role=“img”, and have an accessible description with `aria-label` or `aria-labelledby` jsx-a11y/accessible-emoji
**Description:** Wrapping emoji
---
> wrapping emoji within span

- e2e/specs/st_audio.spec.ts
- lib/streamlit/DeltaGenerator.py
- lib/streamlit/ReportSession.py
- lib/streamlit/ReportThread.py
- lib/streamlit/ScriptRunner.py
- lib/streamlit/__init__.py
- lib/streamlit/cursor.py
- lib/streamlit/errors.py
- lib/tests/streamlit/ReportSession_test.py
- lib/tests/streamlit/add_rows_test.py
- lib/tests/streamlit/caching_test.py
- lib/tests/streamlit/dataframe_styling_test.py
- lib/tests/streamlit/delta_generator_test.py
- lib/tests/streamlit/help_test.py
- lib/tests/streamlit/scriptrunner/ScriptRunner_test.py
- lib/tests/streamlit/streamlit_test.py
- lib/tests/testutil.py
- proto/streamlit/proto/BlockPath.proto
(See https://discuss.streamlit.io/t/crosstalk-between-streamlit-sessions-with-multiple-users/319)
The important changes are all in this one commit: https://github.com/streamlit/streamlit/pull/1015/commits/74eb96af0b2ecbe61b6631bd97960caa18a17b78
The other files are just me fixing tests.
The problem was due to `st.sidebar` actually being a shared object between all sessions. And that shared object contained state that shouldn't be shared (i.e. the `enqueue` function, the current index, etc). 
The bug didn't happen with non-sidebar `st.foo` methods because those didn't have a shared DeltaGenerator. Instead, they used the `_with_dg` wrapper which fetched the correct DeltaGenerator from the ThreadContext.
So the way I fixed this was to make that behavior a 1st-class citizen. That is:
1. …
> Fix sidebar crosstalk between sessions

- lib/streamlit/hashing.py
Issue #857 
We were incorrectly treating `Path`s like `File`s. 
Remove special case hashing for `Path`s and let it be hashed by `__reduce__`
> Don't special case Path hashing

- frontend/src/components/elements/PlotlyChart/PlotlyChart.tsx
We're using an updated version of plotly.js that fixes the bug we hacked around.
> Remove plotly reload hack since plotly.js bug is fixed

- lib/streamlit/DeltaGenerator.py
Copy-pasted docstring from `st.number_input`, but with one difference: the slider format string _can_ produce non-numeric output.
> Fix the st.slider 'format' param docstring

- lib/streamlit/config.py
This allows `streamlit run --global.minCachedMessageSize inf app.py`. Our config.toml accepts `inf` as a value, but streamlit run refuses to run with this value because `inf` is not a valid `int` value.
(Setting `minCachedMessageSize = inf` effectively disables the ForwardMsgCache.)
> Allow disabling ForwardMsgCache from command line

- frontend/src/index.tsx
Issue #365 
Fixes a css conflict between the Plotly Choroplet map and the Baseweb Slider
> Set a classname prefix for atomic styletron css classes

- lib/streamlit/hashing.py
- lib/tests/streamlit/hashing_test.py
**Issue:** #1057
**Description:** Adding custom hashing logic for `numpy.ufunc` types. Added unit test and tested manually on Udacity Demo that was broken (see #1057 for more details)
> Custom hashing logic for numpy.ufunc types

- lib/streamlit/DeltaGenerator.py
- lib/streamlit/hashing.py
o f-strings is a 3.6 feature
o 3.5 doesn't support a trailing comma after "**kwargs" at the end of a
function definition.
CC @nthmost @monchier
> Fix a couple Python 3.5 regressions caught in other work:

- lib/streamlit/server/Server.py
**Issue:** #964 
Streamlit is using tornado for WebSocket. It has overwritten the origin check for CORS, which only allows the configured list of URLs.
However, if the HOST and ORIGIN are the same, it shouldn't invoke the check for the URL list at all. If they are the same value, it should allow the connection.
**Changes**
This will add back the torndado implementation, checking whether HOST and ORIGIN are equal, otherwise then proceed for URL list checks.
---
> Fix for the CORS check

- lib/streamlit/elements/map.py
- lib/tests/streamlit/map_test.py
New test fails before the change, and passes afterwards.
> Fix an incomplete copy for a dict that's then modified.

- .circleci/config.yml
We'll retain testing only against our oldest (3.5) and newest (3.8)
supported Python versions going forward.
FWIW, the "cypress" test continues to be based on a 3.7.4 image because
efforts to upgrade under https://github.com/streamlit/streamlit/pull/1053
failed due to font rendering differences with screenshots. Handling this
upgrade, when needed, will be performed separately, but should not block
removal of running the whole Python suite against 3.7.4.
> Retire python-3.7.4 CircleCI project.

- Makefile
By not passing this, we were violating the "doesn't update the
Pipfile.lock." comment on this Makefile target. I don't see where the
lockfile was later used, and so was most likely providing little
benefit.
Finally, invocation before this change took ~1m13s on my machine when
Pipfile.lock wasn't present, and ~33s when it was. With this change,
it's reliably ~17s.
The big question is if the lockfile was providing any value that I
missed picking up, so that's the major review question.
CC @tconkling
> Pass --skip-lock to pipenv under pipenv-install Makefile target.

- lib/streamlit/DeltaGenerator.py
- lib/streamlit/elements/doc_string.py
- lib/tests/streamlit/delta_generator_test.py
Prior to this PR, something broke the signatures of wrapped DG methods. This was reflected in docs.streamlit.io (where things like `st.text(body)` were written as `st.text()`) and in the Python console (e.g. `help(st.text)`). It was probably broken in IDEs too.
That's because we use some magic to make our signatures cleaner, and something broke that magic. I fixed that now and added tests.
> Clean signatures of wrapped DeltaGenerator methods

- lib/streamlit/DeltaGenerator.py
- lib/tests/streamlit/streamlit_test.py
**Issue:** #975 
**Description:**  Currently, st.json will trip over the use of a nonstandard key in a dictionary, resulting in a confusing and unhelpful traceback to the user.
This PR wraps the conversion to JSON in a try-except block that catches the TypeError that arises from use of weird keys that json.dumps cannot handle.  If triggered, we show a warning to the user that this happened, and then rerun json.dumps with skipkeys=True.  
The resultant data structure will not show the entire data, but the warning should be informative enough to the user to understand why.
---
> Show warning to user and use skipkeys=True if json.dumps causes TypeError

- lib/streamlit/elements/media_proto.py
- lib/tests/streamlit/streamlit_test.py
Fixes `st.video` and `st.audio` crashing on BytesIO and numpy data
> Fix BytesIO, numpy exceptions st.audio/st.video

- lib/streamlit/DeltaGenerator.py
Fix the `st.plotly_chart` docstring to refer to Plotly instead of Altair.
Also fixed a few misspellings.
> st.plotly_chart docs incorrectly refer to Altair

- lib/streamlit/elements/map.py
**Issue:** #1103
**Description:**  Adds "radiusMinPixels" : 3 to the configuration of the st.map element as a way of ensuring the visibility of the map dots.
(This doesn't really optimize the display of points on a map; it's just an easy baby-step of an improvement.)
---
> st.map: hard-code minimum pixel size of 3 for map dots

- lib/streamlit/bootstrap.py
- lib/streamlit/config.py
- lib/streamlit/server/Server.py
- lib/tests/streamlit/config_test.py
**Issue:** fixes https://github.com/streamlit/streamlit/issues/584
**Description:** This PR fixes the linked issue. The option server.address is added to bind the server on a specific interface. The default behaviour that the server binds to all interfaces is keep.
The corresponding unit test is added.
---
> Ability to bind to a server address with server.address config option

- docs/api-examples-source/charts.vega_lite_chart.py
- lib/streamlit/DeltaGenerator.py
- lib/streamlit/__init__.py
**Issue:** fixes https://github.com/streamlit/streamlit/issues/1091
* every time there is a link to [this embedded Streamlit app](https://share.streamlit.io/0.25.0-2JkNY/index.html?id=8jmmXR8iKoZGV4kXaKGYV5), modify the code to include the tooltip interactivity. 
* Modifies docstring for st.write
* Modifies docstring for st.altair_chart
* Modifies docstring for st.vega_lite_chart
* modifies the charts.vega_lite_chart.py, which I suppose generates the embedded Streamlit app _but I'm not really sure..._
---
> Add tooltip in Altair/Vega-lite docstring code

- lib/streamlit/DeltaGenerator.py
- lib/streamlit/config.py
- lib/tests/streamlit/config_test.py
Now that we handle file uploads via HTTP, it's reasonable to raise our default size limit from 50.
> Raise our default max_upload_size to 200 MB

- frontend/src/components/elements/Progress/Progress.tsx
**Issue:** Fixes streamlit/streamlit-old-private/issues/588 .
**Description:** Fixing progressbar animation when switching tabs.
---
> Fixing progressbar animation when switching tabs

- frontend/src/components/widgets/Selectbox/Selectbox.test.tsx
- frontend/src/components/widgets/Selectbox/Selectbox.tsx
**Issue:** https://github.com/streamlit/streamlit/issues/1010
**Description:** Adding a custom `filterOptions` to make the selectbox filter options based on the labels only. The default `filterOptions` function in baseweb filters based on labels or indeces at the same time.
---
> Adding custom filterOptions function to SelectBox

- Makefile
Per https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server
> When on CircleCI, use "yarn run test --runInBand"

- lib/tests/streamlit/scriptrunner/ScriptRunner_test.py
- lib/tests/streamlit/scriptrunner/test_data/widgets_script.py
- Shutdown the first scriptrunner before starting the next 3
- Longer infinite-loop sleep time in widgts_script.py, so we don't wake up too frequently
- Increase our wait_for_widgets_script_deltas timeout to 15 seconds (from 5)
- Throw a detailed error from wait_for_widgets_script_deltas
- On wait_for_widgets timeout, shutdown the scriptrunners so that the Circle job doesn't hang forever.
> Another attempt at test_multiple_scriptrunners timeouts

- e2e/scripts/st_file_uploader.py
- e2e/specs/st_file_uploader.spec.ts
- frontend/cypress/fixtures/example.txt
- frontend/cypress/fixtures/file1.txt
- frontend/cypress/fixtures/file2.txt
- frontend/src/components/widgets/FileUploader/FileUploader.test.tsx
- frontend/src/components/widgets/FileUploader/FileUploader.tsx
- frontend/src/lib/FileUploadClient.test.ts
- frontend/src/lib/FileUploadClient.ts
- lib/streamlit/DeltaGenerator.py
- lib/streamlit/UploadedFileManager.py
- lib/streamlit/file_util.py
- lib/streamlit/server/Server.py
- lib/streamlit/server/UploadFileRequestHandler.py
- lib/tests/streamlit/Server_test.py
- lib/tests/streamlit/UploadFileRequestHandler_test.py
- lib/tests/streamlit/UploadedFileManager_test.py
- lib/tests/streamlit/file_uploader_test.py
- proto/streamlit/proto/FileUploader.proto
This adds basic support for uploading multiple files to a single st.file_uploader
- `st.file_uploader` now has a new flag, `accept_multiple_files`. It defaults to false.
- When `accept_multiple_files` is true, the frontend widget will accept multiple files, and the Python API will return a list of BytesIO/StringIO objects if 1 or more files are uploaded to the widget. (That is, even if the user uploads a single file, the multi-file uploader will always return a list. The single-file variant will never return a list.)
- `UploadedFileManager` now stores lists of files by `session_id/widget_id` key, instead of just single files.
- The e2e test validates the entire round trip of both single and multiple file uploads.
Closes #912 (there are additional API changes to make to file_uploader, but …
> file_uploader: support for multiple files

- lib/streamlit/caching.py
- lib/tests/streamlit/scriptrunner/ScriptRunner_test.py
- lib/tests/streamlit/scriptrunner/test_data/st_cache_script.py
This fixes breakage that I introduced in #1152 
Rather than creating the cache as a local variable in the st.cache wrapper, we instead manage all caches in a global `_MemCaches` class. Each cache is keyed off its wrapped function's fully qualified name, and its contents.
There's a new `ScriptRunner` test that makes sure that caches are reused across multiple runs of the same script.
> Fix st.cache

- lib/tests/streamlit/watcher/LocalSourcesWatcher_test.py
**Issue:** test_just_script was failing
**Description:** When we get the type from the same method we are having `Class 'function'` but if we get the type from another method of the same class we are gonna be having `Class 'method'`.
---
> Fixing test_just_script pytest

- frontend/package.json
- frontend/src/components/elements/VegaLiteChart/VegaLiteChart.tsx
- frontend/yarn.lock
This should fix #755, but I'd love to get @domoritz's opinion if he's available.
I'm looking at this issue now because there have been some reports of long-running Streamlit apps blowing up browser memory:
- https://github.com/streamlit/streamlit/issues/1148
- https://discuss.streamlit.io/t/animation-to-show-only-the-last-n-datapoints/1686/9
In @domoritz's original bug, he suggested that we were using `view.finalize()` incorrectly, though in the version of `vega-embed` we were previously on, there was no separate `finalize` returned from `embed`. Regardless, I've updated vega, vega-lite, and vega-embed to their latest, and we're now using that finalizer. 
This PR also performs finalization at `componentWillUnmount` time, which is consistent with what `react-vega` does: …
> Update vega packages, and do proper view finalization

- lib/streamlit/__init__.py
- lib/tests/streamlit/show_test.py
Add `st.beta` and `st.experimental`, so we can push early features to users by putting them under those namespaces.
For now `st.beta` is empty, and `st.experimental` has only `st.experimental.show` (which was moved from `st.show`. This is OK since that was a hidden/undocumented feature).
> Add experimental and beta namespaces

- docs/troubleshooting/sanity-checks.md
- frontend/package.json
- lib/setup.py
Just up version to 0.57.3 without any other changes. That's because 0.57.3 was just released consisting of 0.57.2, which is already merged into develop, plus a cherrypick that is also already merged into develop.
> Version 0.57.3

- docs/tutorial/create_a_data_explorer_app.md
"Replace the line `st.write('Done!')` with this:" -> "Replace the line `data_load_state.text('Loading data...done!')` with this:"
`st.write('Done!')` isn't used in the data explorer demo app, replaced parts where it's referenced with appropriate text.
PS Absolutely beautiful documentation. Looking more and more forward to using Streamlit for my own apps :)
---
**Issue:** Doc fix 
**Description:** Small documentation update to maintain consistency of language/code.
---
> Update data explorer docs w/ small communication fix

- lib/streamlit/DeltaGenerator.py
`graphviz.DiGraph` -> `graphviz.Digraph`
Fixes #1304
> Fix typo in st.graphviz_chart docstring

- docs/conf.py
- lib/Pipfile
* Adding `sphinx-markdown-tables` extension to our implementation.
* This is a value add, because we can now render tables using raw markdown.
> Add sphinx-markdown-tables

- frontend/src/components/widgets/Plugin/PluginInstance.tsx
- plugin_template/src/PluginWrapper.tsx
- plugin_template/src/StComponentAPI.ts
- plugin_template/src/examples/HelloReact.tsx
- plugin_template/src/examples/RadioButton.tsx
- plugin_template/src/examples/Resizer.tsx
- plugin_template/src/index.tsx
This is a first pass at plugin resizing.
When a plugin updates its DOM, it calls the "updateFrameHeight" callback, which gets sent back to the Streamlit `PluginInstance` host.
> Plugin resizing

- component_template/component_example.py
- frontend/src/components/widgets/CustomComponent/ComponentInstance.tsx
- frontend/src/components/widgets/CustomComponent/ComponentRegistry.tsx
- lib/streamlit/components.py
- proto/streamlit/proto/ComponentInstance.proto
There are two changes in this PR:
- A component's ID is now just its name (rather than a hash).
- On the frontend, `ComponentRegistry` is now responsible for dispatching "ComponentBackMsgs" to their intended `ComponentInstance`. This means that instances don't all install their own event listeners.
> Central message dispatcher for iframe messages

- component_template/.env
- component_template/component_example.py
- component_template/src/MyComponent.tsx
- component_template/src/examples/BuggyComponent.tsx
- component_template/src/examples/DataframeComponent.tsx
- component_template/src/examples/RadioButton.tsx
- component_template/src/examples/Resizer.tsx
- component_template/src/streamlit/index.tsx
- component_template/src/streamlit/withStreamlitConnection.tsx
- frontend/src/components/widgets/CustomComponent/ComponentInstance.tsx
- lib/streamlit/components.py
- proto/streamlit/proto/ComponentInstance.proto
- `yarn start` works to serve components
- I renamed `connectToStreamlit()` -> `withStreamlitConnection()`
> Allow serving components from a URL

- component_template/component_example.py
- component_template/src/VanillaComponent.ts
- component_template/src/index.tsx
- component_template/src/streamlit/index.tsx
- component_template/src/streamlit/streamlit.ts
- component_template/src/streamlit/withStreamlitConnection.tsx
- The Streamlit API is now encapsulated in "streamlit.ts", which doesn't use React.
- Added VanillaComponent, an example component that doesn't use React.
> "Vanilla" component template

- frontend/src/assets/css/custom_components_theme.scss
- frontend/src/assets/css/scrollbars.scss
- frontend/src/assets/css/theme.scss
This adds `frontend/src/assets/css/custom_components_theme.scss` and tweaks a couple of things in our existing theme to make them reusable in the new file.
The idea is that the Custom Components team should build a CSS file from the new SCSS file to ship with our boilerplate:
```
sass frontend/src/assets/css/custom_components_theme.scss streamlit_theme_css
```
(where `sass` [should first be installed](https://sass-lang.com/install))
> Add theme for custom components

- frontend/package.json
Added the required version to yarn resolutions.
> Bump https-proxy-agent to ^2.2.4

- frontend/src/components/widgets/TextArea/TextArea.test.tsx
- frontend/src/components/widgets/TextArea/TextArea.tsx
- lib/streamlit/DeltaGenerator.py
- lib/tests/streamlit/text_area_test.py
- proto/streamlit/proto/TextArea.proto
**Issue:** This PR fixes #277 
- New parameter to set the height manually
- If the height is already passed the user could change the height manually
- Added unit testing
---
> Setting textarea height and unit tests

- lib/streamlit/DeltaGenerator.py
- lib/tests/streamlit/multiselect_test.py
---
**Issue:** [1397 - Multiselect check for defaults goes wrong if not a list](https://github.com/streamlit/streamlit/issues/1397)
- Use `list(iterable)` instead of `[iterable]` to avoid errors (see Issue) because if `iterable` is a tuple, then it converts not to a list, but to a list of tuple. Also [from SO](https://stackoverflow.com/questions/3790848/fastest-way-to-convert-an-iterator-to-a-list) it looks like a preferred practice overall
---
> Change list() cast
